name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'   # daily run
  workflow_dispatch:        # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ZhengPeiRu21/mod-individual-progression
          source_branch: master
          destination_branch: master
          github_token: ${{ secrets.PAT_SYNC }}
